
services:
  # Nome do serviço que vamos subir
  postgres_db:
    image: postgres:15-alpine
    container_name: football_postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: live_games
      POSTGRES_DB: football_alert_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 